### ISSUE TITLE
AUR packages

### ISSUE THREAD

**Issue by lmartinez-mirror** [taiwins/taiwins#137]
Hi, I'm reaching out to know if the AUR package for this project will be updated. `wlroots` has been updated to 0.12.0 for some time now, but since taiwins is stuck on 0.11.0, the package will not build as a result. It will, however, build against 0.12.0 in a clean chroot.

Otherwise I'd be more than happy to take over ownership of the package!

**Comment by xeechou** [comment]
Hi, I just updated the AUR package. It was built against v0.2.0, a far long time ago. In the next month or two the 0.3 version will be out (I just need to finish the Xwayland code), I will update the AUR package then and taiwins will not depend on wlroots anymore.
