### ISSUE TITLE
Touchscreen makes taiwins crash

### ISSUE THREAD

**Issue by deb75** [taiwins/taiwins#142]
Hello,

I built and installed `taiwins` on debian/bulleyes. I start it as advocated.

My laptop screen is a touchscreen, any time I touch it, `taiwins` crashes.

Any idea why ?

**Comment by xeechou** [comment]
Hi, thanks for your info. I don't currently have a touch screen so I can't say for sure, do you have any crash log?

I build taiwins with using address sanitizer by `meson -Db_sanitize build`, so when it crashes, I would know why, make sure to pipe the error log  with `taiwins 2> /path/to/your/log` though, it is awkward because right now I only implemented touch screen input for drm-backend, you can't see the log directly as x11/wayland backend.

Sorry that I am busy implementing xwayland right now, don't have time look into this. it maybe a easy fix though if you don't mind digging into taiwins code.

**Comment by deb75** [comment]
Thanks for your kind answeer.

I will look into this. It seems `taiwins` seems to use `libinput`, so I would love to implement gestures for touchscreen. May you indicate me from where I should start ?

Regards

**Comment by xeechou** [comment]
the chain of events goes like this: `libinput:touch_event -> tw_engine:touch_event -> tw_seat:touch_event`. 

They are scattered in 
- [device.c](https://github.com/taiwins/taiwins/blob/master/libtaiwins/backend/libinput/device.c)
- [seat.c](https://github.com/taiwins/taiwins/blob/master/libtaiwins/engine/seat.c)
- [seat_touch.c](https://github.com/taiwins/twobjects/blob/master/objects/seat/seat_touch.c)

Hope this helps.

**Comment by deb75** [comment]
> Hi, thanks for your info. I don't currently have a touch screen so I can't say for sure, do you have any crash log?
> 
> I build taiwins with using address sanitizer by `meson -Db_sanitize build`, so when it crashes, I would know why, make sure to pipe the error log with `taiwins 2> /path/to/your/log` though, it is awkward because right now I only implemented touch screen input for drm-backend, you can't see the log directly as x11/wayland backends.
> 
> Sorry that I am busy implementing xwayland right now, don't have time look into this. it maybe a easy fix though if you don't mind digging into taiwins code.

When I type `meson -Db_sanitize` I get : 
```
ERROR: Option 'b_sanitize' must have a value separated by equals sign.

Also, this option does not seem to exist in the `meson_options.txt` file
```

**Comment by deb75** [comment]
I used : 
```
meson -Db_sanitize=address build
```
do not know if this is good.

Also, I ge this error : 
```
Run-time dependency lua found: NO (tried pkgconfig and cmake)
```
although I do have lua5.1 installed, what is missing ?

**Comment by deb75** [comment]
I have no a crash log : 
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==24912==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f2974da153e bp 0x7ffcdceba660 sp 0x7ffcdceba640 T0)
==24912==The signal is caused by a READ memory access.
==24912==Hint: address points to the zero page.
    #0 0x7f2974da153e in request_output_device_from_libinput ../libtaiwins/backend/libinput/device.c:42
    #1 0x7f2974da3a33 in handle_device_touch_down_event ../libtaiwins/backend/libinput/device.c:318
    #2 0x7f2974da4310 in handle_device_event ../libtaiwins/backend/libinput/device.c:398
    #3 0x7f2974da5064 in handle_events ../libtaiwins/backend/libinput/input.c:181
    #4 0x7f2974da513c in handle_dispatch_libinput ../libtaiwins/backend/libinput/input.c:195
    #5 0x7f2974cd4491 in wl_event_loop_dispatch (/lib/x86_64-linux-gnu/libwayland-server.so.0+0xb491)
    #6 0x7f2974cd2104 in wl_display_run (/lib/x86_64-linux-gnu/libwayland-server.so.0+0x9104)
    #7 0x5585f8070e3a in main ../compositor/main.c:425
    #8 0x7f29749cbd09 in __libc_start_main ../csu/libc-start.c:308
    #9 0x5585f806ef59 in _start (/usr/local/bin/taiwins+0xef59)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../libtaiwins/backend/libinput/device.c:42 in request_output_device_from_libinput
==24912==ABORTING
```

As soon as I touch the screen

**Comment by xeechou** [comment]
Hi, thanks for taking the time debugging it. Looks like a null deref issue, I will try to looking into this these two days.

**Comment by xeechou** [comment]
Hi deb75, #147 should fix your problem for now. The reason is that I forgot to implement udev device query in drm-backend. But this fix should avoid the crash for you.

**Comment by deb75** [comment]
Many thanks !

I will continue to deep into taiwins

Regards
