### ISSUE TITLE
Set keyboard layout

### ISSUE THREAD

**Issue by deb75** [taiwins/taiwins#150]
I want to set the keyboard layout to "fr". In my config file `.config/taiwins/config.lua` I have : 
```
compositor:keyboard_model('pc105')
compositor:keyboard_layout('fr')
compositor:keyboard_variant('oss')
```
But it has no effect, apparently.

I also have the environnment variables : 
```
XKB_DEFAULT_MODEL=pc105
XKB_DEFAULT_LAYOUT=fr
XKB_DEFAULT_VARIANT=oss
```
which do not seem to help.

**Comment by deb75** [comment]
Actually, it does not seem the config file is read.

I also have the line : 
```
compositor:panel_position("bottom")
```
but the panel (which says "what's up !") is at the top for me.

But the config file is `.config/taiwins/config.lua`

**Comment by xeechou** [comment]
Hi, Taiwins applies xkb options on running lua configs. So setting ENV variables would not help. I guess your problem is that we don't have `compositor:keyboard_variant` options yet, so lua script reports error and nothing applied. You should get a error message like this:

```
/home/developer/.config/taiwins/config.lua:16: attempt to call a nil value (method 'keyboard_variant')
```

But layout and model works if you strip out the variant option. And setting panel position using `compositor:panel_pos`, sorry for the abbreviations.

**Comment by xeechou** [comment]
#152 should fix your issue.

**Comment by deb75** [comment]
Hi,

Thanks for the fix ! I have just retrieved and compiled again `taiwins`.

Alas, with this configuration : 
```lua
os = require "os"
compositor = require "taiwins"

compositor:bind_key("TW_OPEN_CONSOLE", "C-x,C-p")
compositor:lock_in(5)
compositor:wake() --this wakes up the compositor

compositor:panel_position("bottom")

compositor:keyboard_model('pc105')
compositor:keyboard_layout('fr')
compositor:keyboard_varian('oss')

compositor:enable_xwayland(true)

desktop = compositor:desktop()
for _,ws in ipairs(desktop:workspaces()) do
   ws:set_layout('floating')
end
```

I still cannot get the right keyboard layout and the panel position is still at top of the screen.

I launch `taiwins` from console and no errors are reported. It seems the file `~/.config/taiwins/config.lua` is just not read.

**Comment by deb75** [comment]
I added these lines to the config file : 
```
inspect = require "inspect"
compositor = require "taiwins"
print(inspect.inspect(compositor))
```
and I get : 
```
{
  compositor = <function 1>
}
```

so it seems `compositor` is not an object but a function (as far as I understand lua).

**Comment by xeechou** [comment]
Hi deb75,  sorry that the example configuration was not updated, the example was at the age when taiwins was using libweston. Here are some changes:

- you get compositor object from `taiwins.get_compositor()` function, rest are compositor methods.
- Functions like `compositor:lock_in` is not used anymore.
- I got rid of `compositor:wake`, it was a terrible design. 
- there is no more `compositor:desktop` object. Compositor handles the methods.
- There are some other added functions.

You can check out the new [config.lua](https://github.com/taiwins/taiwins/blob/master/docs/config.lua) for an example. Though it is not fully documented yet, if you are interested in the available features, you can take a look at [config_lua.c](https://github.com/taiwins/taiwins/blob/master/compositor/config/config_lua.c#L757). If you think there is new config function you would like to have, you can also submit an issue for it.

**Comment by deb75** [comment]
Thanks for the update :+1:  ,it now works !

At first, I would suggest that configuration errors be reported to the user. I used to use `awesomeWM` whose
configuration file is also lua maiden. Any error during the config file reading step was reported to the user as
a warning/errot notification on the running window manager screen. This would help I think to distinguish between
lua syntaxic errors and real bugs.

Do the shortcuts listed in the `README.md` are still up to date ? can they be overwritten ?

At first sight, some seems to work strangely. For example, `Super+Shift+c` kills all the terminals launched, not just the current focused one.

Also, I would like to improve the configuration : 
- I still get the error : 
```
ERROR occured: cannot open /home/xxxx/.config/taiwins/console.lua: No such file or directory
```
  what should/could I put into this file ?
- my screen is 3000x2000 (hidpi), everything appears quite small, how can I increase the size of objects ?
- touchpad and touchscreen are recognized, but poorly configured : no acceleration for touchpad,
  need to click the touchpad to make a click, instead of just tapping it. Gestures on touchscreen

Is a way to go with taiwins each enhancement ?

Regards

**Comment by xeechou** [comment]
HI,

> Any error during the config file reading step was reported to the user as a warning/error notification on the running window manager screen.

This is the part of logic in taiwins-shell. Server would route those messages to taiwins-shell for displaying notification, but I guess I didn't implement it properly. I will looking into it after Taiwins releases 0.3 this month. Some other urgent issues I have to deal with right now. 

> my screen is 3000x2000 (hidpi), everything appears quite small, how can I increase the size of objects

Could you open another issue for this? The way to do it is configuring your output to use `scale:2` in config.lua. But it is not tested maybe would not work.

> touchpad and touchscreen are recognized, but poorly configured : no acceleration for touchpad, need to click the touchpad to make a click, instead of just tapping it. Gestures on touchscreen. Is a way to go with taiwins for input devices ?

Thanks for letting me know, Libinput config is not presented in taiwins. I will create a new issue for it. 

I am closing this issue as its original problem is solved. 

Regards,
Xichen
