### ISSUE TITLE
taiwins exits few seconds after logging in with gdm

### ISSUE THREAD

**Issue by deb75** [taiwins/taiwins#161]
I added a desktop entry for `taiwins` by adapting the weston one : 

```
[Desktop Entry]
Name=Taiwins
Comment=A modern wayland window manager
Exec=/usr/local/bin/taiwins -s taiwins-shell -c taiwins-console
Type=Application
```
I am successfully logged in but after a few seconds it seems `taiwins` is killed automatically
no matter what I do and I am back to the gdm login manager.

Here is the log from `journalctl -a` : 

```
 gnome-shell[1182]: Connection to xwayland lost
 gdm-launch-environment][816]: pam_unix(gdm-launch-environment:session): session closed for user Debian-gdm
 systemd-logind[719]: Session c1 logged out. Waiting for processes to exit.
 polkitd(authority=local)[716]: Unregistered Authentication Agent for unix-session:c1 (system bus name :1.28, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale fr_FR.UTF-8) (disconnected from bus)
 systemd[1]: session-c1.scope: Succeeded.
 systemd[1]: session-c1.scope: Consumed 6.471s CPU time.
 systemd-logind[719]: Removed session c1.
 /usr/libexec/gdm-wayland-session[1711]: INFO: ../libtaiwins/backend/drm/login/logind.c:176 logind Session removed !
 systemd[929]: pulseaudio.service: Succeeded.
 gdm3[785]: Gdm: Child process -1126 was already dead.
 gdm-wayland-session[1708]: GLib: Source ID 2 was not found when attempting to remove it
 gdm-password][1561]: pam_unix(gdm-password:session): session closed for user xxxxx
```

**Comment by xeechou** [comment]
Thanks for your enthusiasm. Though I am not sure, but when I see this, it looks like it is got something to do with PAM.

> ```
> gdm-launch-environment][816]: pam_unix(gdm-launch-environment:session): session closed for user Debian-gdm
> systemd-logind[719]: Session c1 logged out. Waiting for processes to exit.
> polkitd(authority=local)[716]: Unregistered Authentication Agent for unix-session:c1 (system bus name :1.28, object path >/org/freedesktop/PolicyKit1/AuthenticationAgent, locale fr_FR.UTF-8) (disconnected from bus)
>```

Gdm send session_removed signal to taiwins causing taiwins to exit. I haven't run Taiwins using display manager before, another user has issue with lightdm. I will looking into it, let you know if I found out why.

**Comment by deb75** [comment]
Hi,

Thanks for copiing with all the issues.

This issue is quite odd, I compared the journal messages upon logging into `sway` through `gdm3`, I get the
same messages but `sway` session is not killed : 
```
    gdm-launch-environment][815]: pam_unix(gdm-launch-environment:session): session closed for user Debian-gdm
    systemd-logind[724]: Session c1 logged out. Waiting for processes to exit.
    polkitd(authority=local)[716]: Unregistered Authentication Agent for unix-session:c1 (system bus name :1.28, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale fr_FR.UTF-8) (disconnected from bus)
    systemd[1]: session-c1.scope: Succeeded.
    systemd[1]: session-c1.scope: Consumed 5.609s CPU time.
    systemd-logind[724]: Removed session c1.
    gdm3[782]: Gdm: Child process -1133 was already dead.
```

**Comment by xeechou** [comment]
Hi deb75:

could you verify this? 

in `.libtaiwins/backend/drm/login/logind.c:176`, comment out the line `wl_display_terminate(logind->display)` from the function logind_bus_handle_session_removed() and recompile.

wlroots is not doing anything with this signal.  I suspect taiwins will not get killed this time.

Thanks

**Comment by deb75** [comment]
Hi,

That seems to do the job, no more automatic disconnexion.

Thanks ! It is much simple to start and use `taiwins` from a window manager

**Comment by xeechou** [comment]
@deb75  PR #168 fix the issue and merged.
