### ISSUE TITLE
README fixes

### ISSUE THREAD

**Issue by ghuls** [taiwins/taiwins#73]
modern is written wrong (title and first paragraph):

Change:
> Taiwins, a morden wayland window manager
>
> Taiwins is a dynamic wayland window manager, supports both tiling and floating layout. It is designed to be mordern and modular. It is extensible through lua script and it has built-in shell and widgets implementation through nuklear GUI. It also supports popular tiling window manager features like gapping.

To:
> Taiwins, a modern wayland window manager
>
> Taiwins is a dynamic wayland window manager which supports both tiling and floating layout. It is designed to be modern and modular. It is extensible through lua script and it has built-in shell and widgets implementation through nuklear GUI. It also supports popular tiling window manager features like gapping.

The link to nuklear GUI should be changed to the new location: https://github.com/Immediate-Mode-UI/Nuklear

**Comment by xeechou** [comment]
Thanks.
