### ISSUE TITLE
Building from sources failed

### ISSUE THREAD

**Issue by n0nvme** [taiwins/taiwins#76]
When I tried to build taiwins from sources I've got this error:
```
Build targets in project: 163

wlroots 0.10.0

        systemd: 1
        elogind: 0
       xwayland: 1
    x11_backend: 1
      xcb-icccm: 1
     xcb-errors: 0

taiwins 0.2.0

  Subprojects
       ctypes: YES
        nklua: YES
       pixman: NO Subproject directory not found and pixman.wrap file not found
        tdbus: YES
     twclient: YES
    twobjects: YES
      wlroots: YES

Found ninja-1.10.1 at /usr/bin/ninja
ninja: Entering directory `build'
[412/424] Compiling C object clients/taiwins-shell.p/desktop_shell_shell_lua.c.o
In file included from ../subprojects/nklua/src/nuklear_love.h:26,
                 from ../clients/desktop_shell/shell_lua.c:38:
../subprojects/nklua/src/nuklear_love.c:50:9: note: ‘#pragma message: nuklear already included’
   50 | #pragma message "nuklear already included"
      |         ^~~~~~~
[424/424] Linking target test/tw-test-dummy-surface-gl
```
Any ideas?

**Comment by xeechou** [comment]
Hi n0nvme, that message was added by me for debugging purpose. Generally `#pragma message` would not break the build. You sure the build failed? 

Could you show me the error message? Usually it would go with `error: .... [Werror]`

**Comment by n0nvme** [comment]
Oh, sorry. There are no build errors, but after compiling `build/bin` directory does not appear so I decided there was an error during build. Seems there is the problem in the run section of the README file.


I'll send PR fixing README in a couple of hours.

Do you have IRC channel or giiter for questions like this? I want to try taiwins on my secondary machine and probably I'll have a lot of questions

**Comment by n0nvme** [comment]
Also, installation method from wiki broken. 

```
$ cmake -S. -Bbuild
CMake Error: The source directory "/home/n0nvme/LinuxPorn/taiwins" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by xeechou** [comment]
Hi, CMake is no longer supported as building system due to all my sub-projects are meson based and it is indeed a lot faster to build. As you can see in you command line, there is no more CMakeLists.txt.

**Comment by xeechou** [comment]
Currently I don't have a IRC channel or Gitter for Taiwins. But yeah you are right, I will setup a gitter community this weekend.

**Comment by n0nvme** [comment]
Yeah, I know that you dropped CMake support, but aur package stil trying to buld using CMake

**Comment by xeechou** [comment]
Yeah, sorry I didn't update that one, because I didn't bother updating wlroots as I will drop the dependency next dev-cycle. For now I am building from source as well. If I have enough time, I will update the aur package this weekend.

BTW, I just created new [Gitter](https://gitter.im/taiwins) community. You can post your issues there, I will try to answer the questions when I am online.

**Comment by xeechou** [comment]
@n0nvme The aur package is updated. If there is no more issues relates to building, I am closing this issue.
